### ISSUE TITLE
Error when using plugin (triggered when testing the provided example)

### ISSUE THREAD

**Issue by victornoleto** [biati-digital/glightbox#538]
**Describe the bug**
When testing the plugin the error below appears:

```
vendor.min.js:61444 Uncaught TypeError: slideTriggerNode.getAttribute is not a function
    at GlightboxInit.resize (vendor.min.js:61444:76)
    at vendor.min.js:60832:20
    at vendor.min.js:59932:15
    at Image.<anonymous> (vendor.min.js:59474:9)
```

**Are you able to reproduce the bug in the demo site**
No.

**To Reproduce**
1. npm install glightbox;
2. Imported node_modules/glightbox/dist/js/glightbox.js and node_modules/glightbox/dist/css/glightbox.css;
3. Wrote a javascript file containing the following example:

```
// Instead of using a selector, define the gallery elements
const myGallery = GLightbox({
    elements: [
        {
            'href': 'https://picsum.photos/1200/800',
            'type': 'image',
            'title': 'My Title',
            'description': 'Example',
        },
        {
            'href': 'https://picsum.photos/1200/800',
            'type': 'image',
            'alt': 'image text alternatives'
        },
        {
            'href': 'https://www.youtube.com/watch?v=Ga6RYejo6Hk',
            'type': 'video',
            'source': 'youtube', //vimeo, youtube or local
            'width': 900,
        },
        {
            'content': '<p>This will append some html inside the slide</p>' // read more in the API section
        },
        {
            'content': document.getElementById('inline-example') // this will append a node inside the slide
        },
    ],
    autoplayVideos: true,
});
myGallery.open();
```

**Expected behavior**
Plugin works normally.

**Post the code you are using**
Described above.

**Screenshots**
![2024-10-22_16-55](https://github.com/user-attachments/assets/bf9862bc-d597-4780-9ad2-1b3d25b2fa1a)

**Comment by paul-mckibben** [comment]
I am getting this exact same error.

**Comment by gingerchew** [comment]
@paul-mckibben @victornoleto could either of you make a codepen with a reduced test case? That would help us figure out what is happening.

**Comment by heddn** [comment]
It is the same issue as in https://github.com/biati-digital/glightbox/issues/478
